---
title: "ENVS 193DS Infographic"
date: "June 7, 2026" 
author: "Danielle Sur" 
format: pdf 
editor: source
---

# Set up

```{r}
#| message: false

# loaded in packages
library(tidyverse)
library(janitor)
library(here)
library(webr)
library(ggimage)
library(showtext)

library(dplyr)
library(ggplot2)

# read in data and saved as object called `rxntime`
rxntime   <- readr::read_csv(here::here("data","new-data.csv"))

# read in my data and saved as object called 'pie'
pie <- readr::read_csv(here::here("data","pie-data.csv"))

# imported fonts
# 1st argument: google name, 
# 2nd name: font name in R
font_add_google('Exo 2', 'exo2', 700)
font_add_google('Exo 2', 'exo')

# enabled showtext font rendering
showtext_auto()
```

# Part 3. Visualizing data

## Pie chart

### Cleaning data

```{r}
# created a new object from pie
pie_clean <- pie |>
  # cleaned column names
  clean_names() |> 
  # selected columns of interest
  select(exercise_type, social_interaction, count) |> 
  # changed existing abbreviations
  mutate(social_interaction = case_when(
    social_interaction == "y" ~ "Yes",
    social_interaction == "n" ~ "No"
  )) |> 
  # removed missing values
  drop_na()
```

### Visualization

```{r}
# save plot as an object <- created a pie donut chart with pie_clean df
piechart <- PieDonut(data = pie_clean,
         # pie slices by exercise type, outlined by social interaction
         aes(exercise_type, social_interaction, count = count),
         r0 = 0.3, # inner ring thickness
         r1 = 1, # outer ring thickness
         ratioByGroup = FALSE, # outer circle of the pie adds up to 100%
         title = "Social Interaction Percentage by Exercise Type") # added title

# PNG export
ggsave("pie.png",
       plot = get_last_plot(),
       device = ragg::agg_png,
       bg = "transparent",
       width = 6,
       height = 6,
       units = "in",
       dpi = 300)
```

## Scatter plot

### Cleaning data

```{r}
# created a new object from rxntime
rxntime_clean <- rxntime |> 
  # cleaned column names
  clean_names() |> 
  # selected columns of interest
  select(exercise_type, exercise_duration_min, reaction_time_avg_ms) |> 
  # removed missing values
  drop_na()
```

### Visualization

```{r}
# created image map by exercise type
img_map <- c(
  biking = "images/biking.png",
  volleyball = "images/vb.png",
  walking = "images/walking.png"
)

# new object from clean data frame
rxntime_scatter <- rxntime_clean |>
  # mutated data frame for the addition of icons
  mutate(exercise_type = as.character(exercise_type),
         image = img_map[exercise_type])
```

```{r}
# called showtext
showtext_auto()

# saved plot as an object <- base layer: ggplot
scatterplot <- ggplot(rxntime_scatter,
            # x-axis: exercise duration in minutes
            # y-axis: avg reaction time in milliseconds
            aes(x = exercise_duration_min,
                y = reaction_time_avg_ms)) +
  # first layer: data points represented by custom icons
  geom_image(aes(
    image = image), # icon placement
    size = 0.05, # icon size
    asp = 1) + # square aspect ratio
  # custom theme
  theme_minimal() +
  theme(
    legend.position = "none", # removed legend
    panel.background = element_rect(fill = NA, # removed fill and color
                                     color = NA),
    panel.grid = element_blank(), # removed panel grid
    axis.ticks = element_blank(), # removed axis ticks
    plot.background = element_rect(fill = NA, # removed fill and color
                                   color = NA),
    plot.title = element_text(family = "exo2", # title custom font
                              size = 20),
    axis.title = element_text(family = "exo", # axis title font
                              size = 14),
    axis.title.x = element_text(margin = margin(t = 8)), # text spacing
    axis.title.y = element_text(angle = 0, # repositioned y-axis text
                                margin = margin(r = 8)),
    axis.text = element_text(family = "exo", size = 12)) + # tick label font
  # relabeled x- and y- axes, adding title
  labs(title = "Exercise Duration and Reaction Time",
       x = "Exercise Duration (min)",
       y = "Average Reaction Time (ms)")

# view figure in plots
print(scatterplot)

# PNG export
ggsave("scatterplot.png",
       plot = get_last_plot(), # selected plot to save
       device = ragg::agg_png, # supports alpha
       bg = "transparent", # transparent background
       width = 4, # adjusted width
       height = 3, # adjusted height
       units = "in", # units of plot measurements
       dpi = 300) # resolution
```

## Box / jitter plot

### Cleaning data

```{r}
# created a new object from rxntime
rxntime_box <- rxntime |>
  # cleaned column names
  clean_names() |>
  # selected columns of interest
  select(exercise_type, reaction_time_avg_ms) |>
  # created a new column for images in df
  mutate(image = img_map[exercise_type]) |>
  # capitalized existing abbreviations
  mutate(exercise_type = case_when(
    exercise_type == "volleyball" ~ "Volleyball",
    exercise_type == "biking"    ~ "Biking",
    exercise_type == "walking"   ~ "Walking",
    # assigned exercise types to images
    TRUE ~ as.character(exercise_type)
  )) |>
  # removed missing values
  drop_na()
```

### Visualization

```{r}
# called showtext
showtext_auto()

# save plot as an object <- base layer: ggplot
boxplot <- ggplot(data = rxntime_box,
       # x-axis: exercise type
       # y-axis: mean reaction time
       # color by exercise type
       mapping = aes(x = exercise_type,
                     y = reaction_time_avg_ms,
                     color = exercise_type)) +
  # first layer: boxplot
  geom_boxplot() +
  # second layer: icons and jitter
  geom_image(
    aes(image = image),
    position = position_jitter(width = 0.15, 
                               height = 0),
    size = 0.045, # icon size
    asp = 1) + # icon aspect ratio
  # added title and relabeled x- and y-axes
  labs(title = "Exercise Type and Reaction Time",
       x = "Exercise Type",
       y = "Mean Reaction Time (ms)") +
  # custom theme
  theme_minimal() +
  # removed legend
  theme(legend.position = "none", # removed legend
        panel.background = element_rect(fill = NA, # removed fill and color
                                     color = NA),
        panel.grid = element_blank(), # removed panel grid
        axis.ticks = element_blank(), # removed axis ticks
        plot.background = element_rect(fill = NA, # removed fill and color
                                   color = NA),
        plot.title = element_text(family = "exo2", # title custom font
                              size = 20),
        axis.title = element_text(family = "exo", # axis title font
                              size = 14),
        axis.title.x = element_text(margin = margin(t = 8)), # text spacing
        axis.title.y = element_text(angle = 0, # repositioned y-axis text
                                margin = margin(r = 8)),
        axis.text = element_text(family = "exo", size = 12)) + # tick label font
  # custom colors
  scale_color_manual(values = c("Biking" = "slateblue",
                                "Volleyball" = "dodgerblue",
                                "Walking" = "lightskyblue")) +
  # removed grid lines
  theme(panel.grid = element_blank(),
        axis.line = element_line(color = "black"))

# view figure in plots
print(boxplot)

# PNG export
ggsave("box.png",
       plot = get_last_plot(), # selected plot to save
       device = ragg::agg_png, # supports alpha
       bg = "transparent", # transparent background
       width = 4, # adjusted width
       height = 3, # adjusted height
       units = "in", # units of plot measurements
       dpi = 300) # resolution
```

# Part 4. Write about your process

A classmate on Friday used birds to represent raw data points.